services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      # For development, use the dependencies stage
      target: dependencies
    volumes:
      - ./server:/usr/src/app/server
      - ./data:/usr/src/app/data
      - ./services:/usr/src/app/services
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://data:27017/chatbotdb
    depends_on:
      data:
        condition: service_healthy
    command: npm run dev:server

  data:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
      # - ./data/src/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=chatbotdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3